services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  db_init:
    env_file:
      - ${ENV_FILE:-.env.dev}
    volumes:
      - .:/app

  web:
    env_file:
      - ${ENV_FILE:-.env.dev}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash /app/scripts/start_all.sh
