services:
  db:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  db_init:
    env_file:
      - ${ENV_FILE:-.env.dev}
    volumes:
      - .:/app

  web:
    env_file:
      - ${ENV_FILE:-.env.dev}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: gunicorn -b 0.0.0.0:8000 --workers 2 --timeout 120 --chdir /app/applications/web_app src.app:app --reload

  data_collector:
    env_file:
      - ${ENV_FILE:-.env.dev}
    volumes:
      - .:/app

  data_analyzer:
    env_file:
      - ${ENV_FILE:-.env.dev}
    volumes:
      - .:/app
