from alembic import op
import sqlalchemy as sa

revision = '9170f1073bb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', name='taskstatus'), nullable=False),
    sa.Column('start_address_id', sa.Integer(), nullable=False),
    sa.Column('transfer_address_id', sa.Integer(), nullable=True),
    sa.Column('destination_address_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('drive', 'transit', 'mixed', name='taskmode'), nullable=False),
    sa.Column('drive_part', sa.Enum('first', 'second', name='drivepart'), nullable=True),
    sa.Column('arrive_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('query_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['start_address_id'], ['addresses.id'], ),
    sa.ForeignKeyConstraint(['transfer_address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_tasks_id'), 'route_tasks', ['id'], unique=False)
    op.create_table('route_results',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['route_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('route_results')
    op.drop_index(op.f('ix_route_tasks_id'), table_name='route_tasks')
    op.drop_table('route_tasks')
    op.drop_table('addresses')
    # ### end Alembic commands ###
