from alembic import op
import sqlalchemy as sa

revision = 'cc475c0efd63'
down_revision = '9170f1073bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_tasks', sa.Column('locations', sa.JSON(), nullable=False))
    op.add_column('route_tasks', sa.Column('segment_modes', sa.JSON(), nullable=False))
    op.drop_constraint('route_tasks_start_address_id_fkey', 'route_tasks', type_='foreignkey')
    op.drop_constraint('route_tasks_destination_address_id_fkey', 'route_tasks', type_='foreignkey')
    op.drop_constraint('route_tasks_transfer_address_id_fkey', 'route_tasks', type_='foreignkey')
    op.drop_column('route_tasks', 'mode')
    op.drop_column('route_tasks', 'start_address_id')
    op.drop_column('route_tasks', 'transfer_address_id')
    op.drop_column('route_tasks', 'destination_address_id')
    op.drop_column('route_tasks', 'drive_part')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_tasks', sa.Column('drive_part', postgresql.ENUM('first', 'second', name='drivepart'), autoincrement=False, nullable=True))
    op.add_column('route_tasks', sa.Column('destination_address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('route_tasks', sa.Column('transfer_address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('route_tasks', sa.Column('start_address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('route_tasks', sa.Column('mode', postgresql.ENUM('drive', 'transit', 'mixed', name='taskmode'), autoincrement=False, nullable=False))
    op.create_foreign_key('route_tasks_transfer_address_id_fkey', 'route_tasks', 'addresses', ['transfer_address_id'], ['id'])
    op.create_foreign_key('route_tasks_destination_address_id_fkey', 'route_tasks', 'addresses', ['destination_address_id'], ['id'])
    op.create_foreign_key('route_tasks_start_address_id_fkey', 'route_tasks', 'addresses', ['start_address_id'], ['id'])
    op.drop_column('route_tasks', 'segment_modes')
    op.drop_column('route_tasks', 'locations')
    # ### end Alembic commands ###
